import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dynamic Input Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-300 ">
          <ul className="justify-center space-x-5 flex p-2">
            <Link href={'/'} className=" px-3 py-1 rounded-xl bg-blue-400 font-bold text-white">Form</Link>
            <li className="bg-amber-50 px-3 py-1 rounded-xl text-blue-400 font-bold">History</li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
